name: Build and deploy eleventy website
on:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Execute notebooks and make markdown
        run: |
          pip install -r requirements.txt
          cd jupyter
          jupyter nbconvert --to notebook --execute Question*.ipynb
          python copy_notebooks.py -if ./*.nbconvert.ipynb
          rm ./*.nbconvert.ipynb
          cd ..
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Build Stylus and Eleventy
        run: |
          npm install
          npm ci
          npm run build
        working-directory: 11ty
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './11ty/_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
