name: Build and deploy eleventy website
on:
  push:
    branches:
      - live
jobs:
  build_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build Stylus
        run: |
          npm install
          npm ci
          npm run build:style
          npm run build:11ty
        working-directory: 11ty
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          publish_branch: live
          github_token: ${{ secrets.GITHUB_TOKEN }}
